services:
  tuulikartta:
    container_name: tuulikartta
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - "80:80"
    environment:
      - PROD_MODE=true
      - OSM_TILE_SERVER_URL=/osm_tiles/{z}/{x}/{y}.png
    networks:
      - tuulikartta-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - favourites-db:/var/data
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_PATH=/var/data/favourites.db
    networks:
      - tuulikartta-network

  redis:
    container_name: redis
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - tuulikartta-network
      
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tuulikartta
    networks:
      - tuulikartta-network

networks:
  tuulikartta-network:
    driver: bridge

volumes:
  cache:
    driver: local
  favourites-db:
    driver: local
