server {
    listen 80;

    # windmap frontend
    location / {
        proxy_pass http://tuulikartta:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # OSM tiles proxy
    location /osm_tiles/ {
        proxy_pass http://10.128.39.201:8080/tile/;
        proxy_cache_valid 200 8h;
    }
}